// <auto-generated />
namespace gepv.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class produto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(produto));
        
        string IMigrationMetadata.Id
        {
            get { return "202003242034457_produto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
